apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: "jwt-keycloak"
spec:
  selector:
    matchLabels:
      app: demo-quarkus
  jwtRules:
    - issuer: "http://keycloak-demo-quarkus.localhost/auth/realms/demo-quarkus"
      jwksUri: "http://keycloak.default:8080/auth/realms/demo-quarkus/protocol/openid-connect/certs"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: jwt-require
spec:
  selector:
    matchLabels:
      app: demo-quarkus
  action: ALLOW
  rules:
  - from:
    - source:
        requestPrincipals: ["http://keycloak-demo-quarkus.localhost/auth/realms/demo-quarkus/7745de1c-a85e-4bfe-97fe-42dc2b0b3f65"]
    to:
      - operation:
          paths: [ "/animals"]
  - to:
    # The 2nd rule doesn't have `from` allowing any access (without JWT)
    - operation:
        paths: [ "/q/health/ready"]